package util

import (
	"bufio"
	"io"
)

// NewLineScanner is a simple line-by-line scanner for an io.Reader.
type NewLineScanner struct {
	scanner *bufio.Scanner
	err     error
}

// NewNewLineScanner creates a new NewLineScanner.
func NewNewLineScanner(r io.Reader) *NewLineScanner {
	return &NewLineScanner{
		scanner: bufio.NewScanner(r),
	}
}

// Scan advances the scanner to the next token.
func (s *NewLineScanner) Scan() bool {
	if s.err != nil {
		return false
	}
	ok := s.scanner.Scan()
	s.err = s.scanner.Err()
	return ok
}

// Text returns the most recent token generated by a call to Scan.
func (s *NewLineScanner) Text() string {
	return s.scanner.Text()
}

// Err returns the first non-EOF error that was encountered by the Scanner.
func (s *NewLineScanner) Err() error {
	return s.err
}
